### ISSUE TITLE
Doesn't work. What is the MyBarcodeCapture??

### ISSUE THREAD

**Issue by itsapko** [kony/NFI_FEATURE_APP_BARCODESCANNER#2]
var MyBarcodeScanner = objc.import("MyBarcodeCapture");
It is not native object and this string doesn't work

**Comment by KonyDev** [comment]
Hi @itsapko,
In general You cannot preview NFI based child apps. However you can preview build and run the NFI based applications by following the steps mentioned in [http://docs.kony.com/konylibrary/visualizer/visualizer_user_guide/Default.htm#Foreign_Function_Interface_JS.htm#Running%3FTocPath%3DAdding%2520Functionality%7CIntegrating%2520with%2520Third-party%2520Libraries%2520Using%2520FFI%7C_____5](documentation).

MyBarcodeCapture is class written in native you can find that in iOS native bindings code.

**Comment by itsapko** [comment]
Hi!
When I build the app using my Mac and iPad, Kony Visualizer hangs on step "Generate IPA". In log file I see the next strings:

> [2018-05-24 09:05:16.971] [INFO] vide - [vizClient] Extracting web.zip completed
> [2018-05-24 09:05:16.971] [INFO] vide - [vizClient] Extracted BarcodeScannerNFI v1.0.0 (id: BarcodeScannerNF, vendor: KonyLabs)
> [2018-05-24 09:05:16.971] [INFO] vide - [vizClient] Platform version : 8.2.0.0
> [2018-05-24 09:05:16.971] [INFO] vide - [vizClient] iOS Plug-in version : 8.2.0
> [2018-05-24 09:05:16.971] [INFO] vide - [vizClient] Generating Xcode project file...
> [2018-05-24 09:05:21.975] [INFO] vide - [vizClient] Building new Libraries....
> [2018-05-24 09:06:44.914] [INFO] vide - NotesSyncWorker. Sync upstream started!
> [2018-05-24 09:06:44.920] [DEBUG] vide - pending sync annotation list:
> 
> [2018-05-24 09:06:44.957] [DEBUG] vide - Sync downstream started! Fetch updated comments for project: BarcodeScannerNFI
> [2018-05-24 09:06:44.958] [DEBUG] vide - retrieve comments url: https://visualization.kony.com/api/v1_0/accounts/944ad2ba-2fd3-42bc-a25a-88723d35827e/project/b9ebd00e-e0bf-42c9-bc99-2b87ee1b9b38/comments
> [2018-05-24 09:06:45.716] [DEBUG] vide - No updated comments found
> [2018-05-24 09:06:45.716] [DEBUG] vide - []
> [2018-05-24 09:06:46.999] [DEBUG] vide - [vizClient] In ciNoteUpdatesHandler
> [2018-05-24 09:11:44.915] [INFO] vide - NotesSyncWorker. Sync upstream started!
> [2018-05-24 09:11:44.923] [DEBUG] vide - pending sync annotation list:
> 
> [2018-05-24 09:11:44.963] [DEBUG] vide - Sync downstream started! Fetch updated comments for project: BarcodeScannerNFI
> [2018-05-24 09:11:44.965] [DEBUG] vide - retrieve comments url: https://visualization.kony.com/api/v1_0/accounts/944ad2ba-2fd3-42bc-a25a-88723d35827e/project/b9ebd00e-e0bf-42c9-bc99-2b87ee1b9b38/comments
> [2018-05-24 09:11:45.788] [DEBUG] vide - No updated comments found
> [2018-05-24 09:11:45.789] [DEBUG] vide - []
> [2018-05-24 09:11:47.075] [DEBUG] vide - [vizClient] In ciNoteUpdatesHandler
> [2018-05-24 09:13:37.106] [DEBUG] vide - [vizClient] Console: Switched to tab "Console"
> [2018-05-24 09:13:37.106] [DEBUG] vide - [vizClient] Console: Showing filter options
> [2018-05-24 09:15:32.140] [DEBUG] vide - [vizClient] Console: Switched to tab "Build"
> [2018-05-24 09:15:32.140] [DEBUG] vide - [vizClient] Console: Hiding filter options
> [2018-05-24 09:15:32.140] [DEBUG] vide - [vizClient] Called ontabfocus..buildPaneRender
> [2018-05-24 09:15:32.141] [DEBUG] vide - [vizClient] Console: Switched to tab "Console"
> [2018-05-24 09:15:32.141] [DEBUG] vide - [vizClient] Console: Showing filter options
> [2018-05-24 09:15:37.147] [DEBUG] vide - [vizClient] Console: Switched to tab "Build"
> [2018-05-24 09:15:37.147] [DEBUG] vide - [vizClient] Console: Hiding filter options
> [2018-05-24 09:15:37.147] [DEBUG] vide - [vizClient] Called ontabfocus..buildPaneRender
> [2018-05-24 09:15:37.147] [DEBUG] vide - [vizClient] Console: Switched to tab "Console"
> [2018-05-24 09:15:37.147] [DEBUG] vide - [vizClient] Console: Showing filter options
> [2018-05-24 09:16:44.917] [INFO] vide - NotesSyncWorker. Sync upstream started!
> [2018-05-24 09:16:44.918] [DEBUG] vide - pending sync annotation list:
> 
> [2018-05-24 09:16:44.968] [DEBUG] vide - Sync downstream started! Fetch updated comments for project: BarcodeScannerNFI
> [2018-05-24 09:16:44.968] [DEBUG] vide - retrieve comments url: https://visualization.kony.com/api/v1_0/accounts/944ad2ba-2fd3-42bc-a25a-88723d35827e/project/b9ebd00e-e0bf-42c9-bc99-2b87ee1b9b38/comments
> [2018-05-24 09:16:45.816] [DEBUG] vide - No updated comments found
> [2018-05-24 09:16:45.816] [DEBUG] vide - []
> [2018-05-24 09:16:47.178] [DEBUG] vide - [vizClient] In ciNoteUpdatesHandler
> [2018-05-24 09:19:17.218] [DEBUG] vide - [vizClient] Console: Switched to tab "Build"
> [2018-05-24 09:19:17.218] [DEBUG] vide - [vizClient] Console: Hiding filter options
> [2018-05-24 09:19:17.218] [DEBUG] vide - [vizClient] Called ontabfocus..buildPaneRender
> [2018-05-24 09:21:44.918] [INFO] vide - NotesSyncWorker. Sync upstream started!
> [2018-05-24 09:21:44.920] [DEBUG] vide - pending sync annotation list:
> 
> [2018-05-24 09:21:44.970] [DEBUG] vide - Sync downstream started! Fetch updated comments for project: BarcodeScannerNFI
> [2018-05-24 09:21:44.971] [DEBUG] vide - retrieve comments url: https://visualization.kony.com/api/v1_0/accounts/944ad2ba-2fd3-42bc-a25a-88723d35827e/project/b9ebd00e-e0bf-42c9-bc99-2b87ee1b9b38/comments
> [2018-05-24 09:21:45.789] [DEBUG] vide - No updated comments found
> [2018-05-24 09:21:45.789] [DEBUG] vide - []
> [2018-05-24 09:21:47.262] [DEBUG] vide - [vizClient] In ciNoteUpdatesHandler
>
